### ISSUE TITLE
Remove ttp:mediaDuration.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml3#18]
Alongside the removal of mediaDuration in #323 we need to remove mediaDuration as discussed at TPAC 2017. The indefinite end time can be resolved using clipBegin (or its renamed equivalent) instead as per #483.

**Comment by skynavga** [comment]
Closing this issue with no further action since `ttp:mediaDuration` has already been removed (https://github.com/w3c/ttml2/commit/a40894c18dfeae749efa7922490f99a71083221a).
