### ISSUE TITLE
Update profile support waterfall.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml3#26]
Update support for prior profile versions, i.e., add support for [ttml2] profiles (as well as [dfxp]).

**Comment by nigelmegitt** [comment]
This kind of dependency seems like avoidable work for future versions if we can factor out the publication of new profile versions into a separate module; I suggest we consider the implications of such an approach.

**Comment by skynavga** [comment]
Perhaps in the future, but not at this time. In any case, this change is dealing with core profile definitions, something that cannot be modularized on its own. I do expect modules to define new feature designators. Unless you have a substantive change in mind, please approve this PR.

**Comment by nigelmegitt** [comment]
@skynavga My comment was on the issue before I'd seen there was a pull request. It might be helpful to allow some time for the issue to settle in before raising the pull request, when it's significant like this. I will review the pull request separately.
