### ISSUE TITLE
rubyOffset and line-spacing

### ISSUE THREAD

**Issue by r12a** [w3c/ttml3#8]
10.2.35 tts:rubyOffset
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOffset

How does ruby offset interact with line spacing?  Are we all covered there?

**Comment by skynavga** [comment]
Closing this issue as `tts:rubyOffset` is no longer present, and no strong use case for it has appeared. If someone wishes to add it, file a new issue to that end and reference this (and other now closed issues related to `tts:rubyOffset`).
